version: "3.9"

services:
  newspick-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: newspick-ui
    ports:
      - "7860:7860"
    volumes:
      - ${HOME}/Downloads:/app/app/final_videos
    restart: unless-stopped
