import json
import os
import subprocess
import sys
import threading
from pathlib import Path

from flask import Flask, jsonify, render_template, request, send_from_directory

BASE_DIR = Path(__file__).resolve().parent
PIPELINE_INPUT_PATH = BASE_DIR / "pipeline_input.py"
CONFIG_PATH = BASE_DIR / "config.json"
INPUT_IMAGE_DIR = BASE_DIR / "InputImage"
FINAL_VIDEO_DIR = BASE_DIR / "final_videos"

app = Flask(__name__, static_folder="static", template_folder="templates")

_state_lock = threading.Lock()
_state = {
    "proc": None,
    "running": False,
    "logs": [],
    "returncode": None,
}


def _to_bool(v, default=False):
    if v is None:
        return default
    if isinstance(v, bool):
        return v
    return str(v).strip().lower() in {"1", "true", "yes", "on"}


def _latest_video():
    if not FINAL_VIDEO_DIR.exists():
        return None
    vids = sorted(FINAL_VIDEO_DIR.glob("*.mp4"), key=lambda p: p.stat().st_mtime, reverse=True)
    return vids[0] if vids else None


def _load_pipeline_input():
    namespace = {}
    if PIPELINE_INPUT_PATH.exists():
        code = PIPELINE_INPUT_PATH.read_text(encoding="utf-8")
        exec(compile(code, str(PIPELINE_INPUT_PATH), "exec"), namespace)
    return namespace


def _load_config():
    if not CONFIG_PATH.exists():
        return {}
    return json.loads(CONFIG_PATH.read_text(encoding="utf-8"))


def _write_pipeline_input(values):
    lines = [
        '"""',
        "User-editable pipeline inputs.",
        "Generated by Web UI.",
        '"""',
        "",
        f"CONTENT = {values['CONTENT']!r}",
        "",
        f"AI_CONTENT = {values['AI_CONTENT']}",
        f"VOICEOVER_SIZE = {values['VOICEOVER_SIZE']!r}",
        f"VOICE_NAMES = {values['VOICE_NAMES']!r}",
        "",
        f"LANGUAGE = {values['LANGUAGE']!r}",
        f"VIDEO_ORIENTATION = {values['VIDEO_ORIENTATION']!r}",
        f"INPUT_THEME = {values['INPUT_THEME']!r}",
        "",
        f"ENABLE_HEADING = {values['ENABLE_HEADING']}",
        f"HEADING_INPUT = {values['HEADING_INPUT']!r}",
        "",
        f"SUBTITLES_ENABLED = {values['SUBTITLES_ENABLED']}",
        "",
        f"IMAGE_REVIEW_AI = {values['IMAGE_REVIEW_AI']}",
        f"IMAGE_LOOP_SECONDS = {values['IMAGE_LOOP_SECONDS']}",
        "",
        f"INPUT_VIDEOS = {values['INPUT_VIDEOS']!r}",
        f"INPUT_VIDEOS_POSITION = {values['INPUT_VIDEOS_POSITION']!r}",
        f"INPUT_VIDEOS_AUDIO = {values['INPUT_VIDEOS_AUDIO']}",
        "",
        f"DEFAULT_AUDIO = {values['DEFAULT_AUDIO']!r}",
        "",
    ]
    PIPELINE_INPUT_PATH.write_text("\n".join(lines), encoding="utf-8")


def _write_config_features(config, enable_image_download, enable_image_generation):
    cfg = dict(config)
    features = dict(cfg.get("features", {}))
    features["enable_image_download"] = bool(enable_image_download)
    features["enable_image_generation"] = bool(enable_image_generation)
    cfg["features"] = features
    CONFIG_PATH.write_text(json.dumps(cfg, indent=4, ensure_ascii=False), encoding="utf-8")


def _save_uploaded_images(files):
    if not files:
        return
    INPUT_IMAGE_DIR.mkdir(parents=True, exist_ok=True)
    for p in INPUT_IMAGE_DIR.iterdir():
        if p.is_file():
            p.unlink()
    for f in files:
        name = Path(f.filename).name
        if not name:
            continue
        (INPUT_IMAGE_DIR / name).write_bytes(f.read())


def _parse_input_videos(text):
    out = []
    for raw in (text or "").splitlines():
        p = raw.strip()
        if p:
            out.append({"path": p, "video_audio": False})
    return out


def _log_reader(proc):
    with _state_lock:
        _state["running"] = True
        _state["logs"] = []
        _state["returncode"] = None
    if proc.stdout is None:
        return
    for line in proc.stdout:
        with _state_lock:
            _state["logs"].append(line.rstrip("\n"))
            if len(_state["logs"]) > 1500:
                _state["logs"] = _state["logs"][-1000:]
    rc = proc.wait()
    with _state_lock:
        _state["returncode"] = rc
        _state["running"] = False
        _state["proc"] = None


@app.get("/")
def home():
    return render_template("index.html")


@app.get("/api/config")
def api_config():
    pi = _load_pipeline_input()
    cfg = _load_config()
    features = cfg.get("features", {})
    return jsonify(
        {
            "content": str(pi.get("CONTENT", "")),
            "ai_content": bool(pi.get("AI_CONTENT", True)),
            "voiceover_size": str(pi.get("VOICEOVER_SIZE", "small")),
            "voice_names": pi.get("VOICE_NAMES", ["Schedar"]),
            "language": str(pi.get("LANGUAGE", "hindi")),
            "video_orientation": str(pi.get("VIDEO_ORIENTATION", "vertical")),
            "input_theme": str(pi.get("INPUT_THEME", "pg")),
            "enable_heading": bool(pi.get("ENABLE_HEADING", True)),
            "heading_input": str(pi.get("HEADING_INPUT", "")),
            "subtitles_enabled": bool(pi.get("SUBTITLES_ENABLED", True)),
            "image_review_ai": bool(pi.get("IMAGE_REVIEW_AI", True)),
            "image_loop_seconds": int(pi.get("IMAGE_LOOP_SECONDS", 10)),
            "input_videos": pi.get("INPUT_VIDEOS", []),
            "input_videos_position": str(pi.get("INPUT_VIDEOS_POSITION", "prefix")),
            "input_videos_audio": bool(pi.get("INPUT_VIDEOS_AUDIO", False)),
            "default_audio": str(pi.get("DEFAULT_AUDIO", "BreakinNews-2.mp3")),
            "enable_image_download": bool(features.get("enable_image_download", True)),
            "enable_image_generation": bool(features.get("enable_image_generation", True)),
        }
    )


@app.post("/api/run")
def api_run():
    with _state_lock:
        if _state["running"]:
            return jsonify({"ok": False, "error": "Pipeline already running"}), 409

    form = request.form
    content = (form.get("content") or "").strip()
    if not content:
        return jsonify({"ok": False, "error": "Content is required"}), 400

    cfg = _load_config()

    values = {
        "CONTENT": content,
        "AI_CONTENT": _to_bool(form.get("ai_content"), False),
        "VOICEOVER_SIZE": (form.get("voiceover_size") or "small").strip().lower(),
        "VOICE_NAMES": [x.strip() for x in (form.get("voice_names") or "Schedar").split(",") if x.strip()],
        "LANGUAGE": (form.get("language") or "hindi").strip().lower(),
        "VIDEO_ORIENTATION": (form.get("video_orientation") or "vertical").strip().lower(),
        "INPUT_THEME": (form.get("input_theme") or "pg").strip().lower(),
        "ENABLE_HEADING": _to_bool(form.get("enable_heading"), False),
        "HEADING_INPUT": form.get("heading_input") or "",
        "SUBTITLES_ENABLED": _to_bool(form.get("subtitles_enabled"), False),
        "IMAGE_REVIEW_AI": _to_bool(form.get("image_review_ai"), False),
        "IMAGE_LOOP_SECONDS": int(form.get("image_loop_seconds") or 10),
        "INPUT_VIDEOS": _parse_input_videos(form.get("input_videos") or ""),
        "INPUT_VIDEOS_POSITION": (form.get("input_videos_position") or "prefix").strip().lower(),
        "INPUT_VIDEOS_AUDIO": _to_bool(form.get("input_videos_audio"), False),
        "DEFAULT_AUDIO": form.get("default_audio") or "BreakinNews-2.mp3",
    }

    _write_pipeline_input(values)
    _write_config_features(
        cfg,
        _to_bool(form.get("enable_image_download"), False),
        _to_bool(form.get("enable_image_generation"), False),
    )
    _save_uploaded_images(request.files.getlist("input_images"))

    env = os.environ.copy()
    env["PYTHONUNBUFFERED"] = "1"

    proc = subprocess.Popen(
        [sys.executable, "main.py"],
        cwd=str(BASE_DIR),
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
    )

    with _state_lock:
        _state["proc"] = proc
        _state["running"] = True
        _state["logs"] = []
        _state["returncode"] = None

    t = threading.Thread(target=_log_reader, args=(proc,), daemon=True)
    t.start()

    return jsonify({"ok": True})


@app.get("/api/progress")
def api_progress():
    with _state_lock:
        running = _state["running"]
        logs = list(_state["logs"][-300:])
        returncode = _state["returncode"]

    latest = _latest_video()
    video_url = f"/videos/{latest.name}" if latest else ""
    return jsonify(
        {
            "running": running,
            "logs": logs,
            "returncode": returncode,
            "latest_video": latest.name if latest else "",
            "latest_video_url": video_url,
        }
    )


@app.get("/videos/<path:filename>")
def videos(filename):
    return send_from_directory(FINAL_VIDEO_DIR, filename)


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=7860, debug=False)
